# Generated by Django 5.2.3 on 2025-08-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Untitled Task', max_length=255),
            preserve_default=False,
        ),
    ]
